/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 office_sphere.glb 
Author: Jonas André (https://sketchfab.com/bingiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-sphere-d820382f18e34460b069a74d9f5d57d0
Title: Office Sphere
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function OfficeSphere(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/office_sphere.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group
            name="b220ff2607a24d369bd8f15de327a853fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Schnee" rotation={[-1.612, 0.523, 0.021]}>
                  <mesh
                    name="Schnee_Schnee_0"
                    geometry={nodes.Schnee_Schnee_0.geometry}
                    material={materials.Schnee}
                  />
                </group>
                <group
                  name="Sonne"
                  position={[0, 0, -2100.799]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Sonne_Planet_0"
                    geometry={nodes.Sonne_Planet_0.geometry}
                    material={materials.Planet}
                  />
                </group>
                <group name="Kuppel" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Kuppel_Kuppel_0"
                    geometry={nodes.Kuppel_Kuppel_0.geometry}
                    material={materials.Kuppel}
                  />
                </group>
                <group
                  name="Tischbein_v2_01"
                  position={[12.067, 0.351, 2.308]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.547, 0.36, 0.143]}
                >
                  <mesh
                    name="Tischbein_v2_01_Metall_0"
                    geometry={nodes.Tischbein_v2_01_Metall_0.geometry}
                    material={materials.Metall}
                  />
                </group>
                <group
                  name="Tischbein_v2_02"
                  position={[-11.794, 0.351, 2.308]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group
                    name="Object_11"
                    rotation={[0, 0, Math.PI / 2]}
                    scale={[-0.547, 0.36, 0.143]}
                  >
                    <mesh
                      name="Tischbein_v2_02_Metall_0"
                      geometry={nodes.Tischbein_v2_02_Metall_0.geometry}
                      material={materials.Metall}
                    />
                  </group>
                </group>
                <group
                  name="Tisch"
                  position={[0.03, 8.293, 3.854]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.701, 0.701, 0.279]}
                >
                  <mesh
                    name="Tisch_Tischplatte_0"
                    geometry={nodes.Tisch_Tischplatte_0.geometry}
                    material={materials.Tischplatte}
                  />
                </group>
                <group
                  name="Stuhlbein"
                  position={[5.451, -0.595, 10.092]}
                  rotation={[-Math.PI / 2, 0, 0.436]}
                  scale={0.692}
                >
                  <group name="Object_16" position={[0, 0, -8.302]}>
                    <mesh
                      name="Stuhlbein_Metall_0"
                      geometry={nodes.Stuhlbein_Metall_0.geometry}
                      material={materials.Metall}
                    />
                  </group>
                </group>
                <group
                  name="Sitz"
                  position={[5.475, 5.474, 10.092]}
                  rotation={[-Math.PI / 2, 0, 0.436]}
                >
                  <mesh
                    name="Sitz_Stuhl_0"
                    geometry={nodes.Sitz_Stuhl_0.geometry}
                    material={materials.Stuhl}
                  />
                </group>
                <group
                  name="Lehne"
                  position={[6.904, 10.271, 13.156]}
                  rotation={[-2.854, -0.421, 0.12]}
                >
                  <mesh
                    name="Lehne_Stuhl_0"
                    geometry={nodes.Lehne_Stuhl_0.geometry}
                    material={materials.Stuhl}
                  />
                </group>
                <group
                  name="Baum"
                  position={[-17.255, 7.324, 18.032]}
                  rotation={[-Math.PI / 2, 0, -0.617]}
                  scale={0.441}
                >
                  <mesh
                    name="Baum_Baum_0"
                    geometry={nodes.Baum_Baum_0.geometry}
                    material={materials.Baum}
                  />
                </group>
                <group
                  name="Boden001"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={1.009}
                >
                  <mesh
                    name="Boden001_Boden_0"
                    geometry={nodes.Boden001_Boden_0.geometry}
                    material={materials.Boden}
                  />
                </group>
                <group
                  name="Blatt_1"
                  position={[2.394, 8.899, -10.623]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Blatt_1_Papier_0"
                    geometry={nodes.Blatt_1_Papier_0.geometry}
                    material={materials.Papier}
                  />
                </group>
                <group
                  name="Blatt_2"
                  position={[3.411, 8.925, -10.623]}
                  rotation={[-Math.PI / 2, 0, -0.611]}
                >
                  <mesh
                    name="Blatt_2_Papier_0"
                    geometry={nodes.Blatt_2_Papier_0.geometry}
                    material={materials.Papier}
                  />
                </group>
                <group
                  name="Stift"
                  position={[4.841, 8.886, -9.534]}
                  rotation={[-3.083, -0.436, 0]}
                  scale={0.156}
                >
                  <mesh
                    name="Stift_Display_Pen_0"
                    geometry={nodes.Stift_Display_Pen_0.geometry}
                    material={materials.Display_Pen}
                  />
                </group>
                <group
                  name="St��nder"
                  position={[-6.993, 8.903, -8.318]}
                  rotation={[-Math.PI / 2, 0, -0.873]}
                  scale={[0.23, 0.23, 0.081]}
                >
                  <mesh
                    name="St��nder_Metall_0"
                    geometry={nodes["St��nder_Metall_0"].geometry}
                    material={materials.Metall}
                  />
                </group>
                <group
                  name="Display"
                  position={[-8.733, 10.696, -10.391]}
                  rotation={[2.496, -0.59, -1.968]}
                  scale={[0.23, 0.23, 0.081]}
                >
                  <mesh
                    name="Display_Display_Pen_0"
                    geometry={nodes.Display_Display_Pen_0.geometry}
                    material={materials.Display_Pen}
                  />
                </group>
                <group
                  name="Holo_Tastatur"
                  position={[-7.169, 9.004, -8.527]}
                  rotation={[-1.528, 0.036, -0.873]}
                  scale={[2.51, 0.23, 0.081]}
                >
                  <group name="Object_39" position={[3.256, 0, -2.603]}>
                    <mesh
                      name="Holo_Tastatur_Holo_0"
                      geometry={nodes.Holo_Tastatur_Holo_0.geometry}
                      material={materials.Holo}
                    />
                  </group>
                </group>
                <group
                  name="Particle_View_001"
                  rotation={[-Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/office_sphere.glb");

export default OfficeSphere;
