name: Deploy to Dev
run-name: ${{ github.actor }} test
on:
  push:
    branches:
      - dev
      - main

permissions: #https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#requesting-the-access-token
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_ROLE_ARN }}
          role-session-name: pipelinerolesession
          aws-region: ${{ env.DEFAULT_AWS_REGION }}

      - name: Copy files to the test website with the AWS CLI
        run: aws s3 ls
